server:
  port: 8088
  # http://blog.csdn.net/isea533/article/details/50359390
  ##参考https://github.com/alibaba/druid/wiki/%E9%85%8D%E7%BD%AE_DruidDataSource%E5%8F%82%E8%80%83%E9%85%8D%E7%BD%AE
spring:
  datasource:
     name: workflow
     ## 使用druid数据源
     type: com.alibaba.druid.pool.DruidDataSource
     driver-class-name: com.mysql.jdbc.Driver
     url: jdbc:mysql://127.0.0.1:3306/bug-manage?useUnicode=true&characterEncoding=utf8
     username: bug-manage
     password: bug-manage
     #配置初始化大小、最小、最大
     maxActive: 20
     initialSize: 1
     minIdle: 3
     maxWait: 60000
     time-between-eviction-runs-millis: 60000
     minEvictableIdleTimeMillis: 300000
     test-while-idle: true
     test-on-borrow: false
     test-on-return: false
  #redis
  redis:
    host: localhost
    port: 6379
    pool:
      max-active: 8
      max-wait: 1
      max-idle: 8


